server:
  port: 8001
  servlet:
    context-path: /provide
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud_dep_8001
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: microservicecloud-dep     ##这个作为在eureka注册的名字
  profiles: dev
eureka:
  client:
    service-url:
       defaultZone: http://eureka7001.com:7001/eureka/      ###这里必须添加/eureka/

#集群配置 defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7003/eureka/,http://eureka7003.com:7003/eureka/
#defaultZone:map集合的key必须这个

  instance:
    instance-id: microservicecloud-provide-dep-8001
    prefer-ip-address: true
    status-page-url-path: ${management.server.servlet.context-path}/actuator/info    

# 当配置context-path时，需要配置才能访问，${management.server.servlet.context-path}端口会自动改变

info:
  app.name: 1
  app.company: 2
  
management:
  server:
    servlet:
      context-path: /management      #必须加 /   ,不能和tomcat配置的端口一样,必须配置端口和端口一起使用的
    port: 9001

---
    
server:
  port: 8002
  servlet:
    context-path: /provide
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud_dep_8002
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: microservicecloud-dep     ##这个作为在eureka注册的名字
  profiles: test
eureka:
  client:
    service-url:
       defaultZone: http://eureka7001.com:7001/eureka/      ###这里必须添加/eureka/

#集群配置 defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7003/eureka/,http://eureka7003.com:7003/eureka/
#defaultZone:map集合的key必须这个

  instance:
    instance-id: microservicecloud-provide-dep-8002
    prefer-ip-address: true
    status-page-url-path: ${management.server.servlet.context-path}/actuator/info    

# 当配置context-path时，需要配置才能访问，${management.server.servlet.context-path}端口会自动改变

info:
  app.name: 1
  app.company: 2
  
management:
  server:
    servlet:
      context-path: /management      #必须加 /   ,不能和tomcat配置的端口一样,必须配置端口和端口一起使用的
    port: 9001